application: canvas-benchmark
version: 1
runtime: python27
api_version: 1
threadsafe: no

skip_files:
- src/.*
- .*\.sh
- .*\.pyc

handlers:
- url: /static
  static_dir: static
- url: .*
  script: gae-main.py